# EXT:thierolf/Configuration/RTE/Default.yaml
imports:
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }

editor:
  config:
    contentsCss:
      - "EXT:thierolf/Resources/Public/StyleSheet/rte.css"

    stylesSet:
      - { name: "Btn Blau", element: "a", attributes: { class: "btn btn-primary rounded-0"} }
      - { name: "Btn Schwarz", element: "a", attributes: { class: "btn btn-dark rounded-0"} }
      - { name: "Btn Weiß", element: "a", attributes: { class: "btn btn-outline-dark rounded-0"} }
      - { name: "Btn BG-Weiß", element: "a", attributes: { class: "btn btn-light rounded-0"} }
      - { name: "Btn Blau 100%", element: "a", attributes: { class: "btn btn-primary rounded-0 w-100 "} }
      - { name: "Btn Schwarz 100%", element: "a", attributes: { class: "btn btn-dark rounded-0 w-100"} }
      - { name: "Btn Weiß 100%", element: "a", attributes: { class: "btn btn-outline-dark rounded-0 w-100"} }
      - { name: "Btn BG-Weiß 100%", element: "a", attributes: { class: "btn btn-light rounded-0 w-100"} }
      - { name: "Abstand Innen", element: "a", attributes: { class: "px-5"} }
      - { name: "Abstand Rechs", element: "a", attributes: { class: "pe-5"} }
      - { name: "Abstand Links", element: "a", attributes: { class: "ps-5"} }
      - { name: "Pfeil Rechts", element: "a", attributes: { class: "fa-solid fa-chevron-right pe-5"} }
      - { name: "Tabelle gestreift", element: "table", attributes: { class: "table table-striped"} }
      - { name: "Tabelle hover", element: "table", attributes: { class: "table table-hover"} }
      - { name: "Tabelle mit Linien", element: "table", attributes: { class: "table table-bordered"} }
      - { name: "Tabelle ohne Linien", element: "table", attributes: { class: "table table-borderless"} }
      - { name: "Tabelle Schmal", element: "table", attributes: { class: "table table-sm"} }
    format_tags: "p;h1;h2;h3;h4;h5;div"
   
    toolbar:
      items:
        - clipboard
        - removeFormat
        - undo
        - redo
        # grouping separator
        - '|'
        - find
        - selectAll
        - '|'
        - link
        - insertTable
        - tableColumn
        - tableRow
        - mergeTableCells
        - tableProperties
        - tableSettings
        - tableCellProperties
        - toggleTableCaption
        - '|'
        - sourceEditing
        - showBlocks
        - horizontalLine
        # line break
        - '-'
        - bold
        - italic
        - underline
        - strikethrough
        - subscript
        - superscript
        - softhyphen
        - '|'
        - bulletedList
        - numberedList
        - blockQuote
        - indent
        - outdent
        - alignment
        - '|'
        - specialCharacters
        - '-'
        - style
        - heading
    
    alignment:
      options:
        - { name: 'left', className: 'text-start' }
        - { name: 'center', className: 'text-center' }
        - { name: 'right', className: 'text-end' }
        - { name: 'justify', className: 'text-justify' }

    justifyClasses:
      - text-left
      - text-center
      - text-right
      - text-justify

    extraPlugins:
      - justify
      - font
      - find
      - bidi
      - autolink
      - wordcount
      - autogrow


    #RTE default config removes image plugin - restore it:
    removePlugins:
      - image

    removeButtons:
      - Font
      - FontSize
